apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: cinema-app
type: Opaque
stringData:
  Jwt__Key: "secret-key-here"
  Jwt__Issuer: "cinema-app"
  Jwt__Audience: "cinema-app-clients"
