apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  namespace: cinema-app
  labels:
    app: notifications-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
        - name: notifications-service
          image: ghcr.io/linaan0/cinema-app-notifications:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: notifications-config
            - secretRef:
                name: jwt-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
